steps:
  notify_on_failure:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'cyberbus-translations CI build failed: ${CI_PIPELINE_URL}' ntfy.sh/cyberbus_drone_ci"
    when:
      - event: pull_request
        status: failure
